(()=>{
'use strict';
const STORAGE_KEY='testCodeChatEncryptedState';
const AAD=new TextEncoder().encode('testCode-chat-local-v1');
const ROLES=new Set(['system','user','assistant']);
const b64url=(bytes)=>{let text='';for(const byte of bytes)text+=String.fromCharCode(byte);return btoa(text).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')};
const fromB64url=(value)=>{const normalized=String(value||'').replace(/-/g,'+').replace(/_/g,'/');const raw=atob(normalized+'==='.slice((normalized.length+3)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0))};
const clone=(value)=>JSON.parse(JSON.stringify(value));
const text=(value)=>typeof value==='string'?value:'';
function createDefaultState(){return{version:1,settings:{apiEndpoint:'',apiKey:'',defaultModel:''},conversations:[],activeConversationId:null}}
function normalizeMessage(value){if(!value||typeof value!=='object'||!ROLES.has(value.role)||typeof value.content!=='string')return null;return{id:text(value.id),role:value.role,content:value.content,createdAt:text(value.createdAt)}}
function normalizeConversation(value){if(!value||typeof value!=='object'||typeof value.id!=='string'||!value.id)return null;return{id:value.id,title:text(value.title),createdAt:text(value.createdAt),updatedAt:text(value.updatedAt),messages:Array.isArray(value.messages)?value.messages.map(normalizeMessage).filter(Boolean):[]}}
function normalizeState(value){const source=value&&typeof value==='object'?value:{},settings=source.settings&&typeof source.settings==='object'?source.settings:{},conversations=Array.isArray(source.conversations)?source.conversations.map(normalizeConversation).filter(Boolean):[];const ids=new Set(conversations.map(c=>c.id));return{version:1,settings:{apiEndpoint:text(settings.apiEndpoint),apiKey:text(settings.apiKey),defaultModel:text(settings.defaultModel)},conversations,activeConversationId:typeof source.activeConversationId==='string'&&ids.has(source.activeConversationId)?source.activeConversationId:null}}
async function importKey(rawKey){const bytes=rawKey instanceof Uint8Array?rawKey:new Uint8Array(rawKey||[]);if(bytes.length!==32)throw new Error('vault key must be 32 bytes');return crypto.subtle.importKey('raw',bytes,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptState(state,rawKey){const iv=new Uint8Array(12);crypto.getRandomValues(iv);const bytes=new TextEncoder().encode(JSON.stringify(normalizeState(state)));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:AAD},await importKey(rawKey),bytes);return{type:'testcode-chat-local',version:1,iv:b64url(iv),ciphertext:b64url(new Uint8Array(encrypted))}}
async function decryptState(envelope,rawKey){if(!envelope||envelope.type!=='testcode-chat-local'||envelope.version!==1||!envelope.iv||!envelope.ciphertext)throw new Error('invalid chat envelope');const decrypted=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64url(envelope.iv),additionalData:AAD},await importKey(rawKey),fromB64url(envelope.ciphertext));return normalizeState(JSON.parse(new TextDecoder().decode(decrypted)))}
function loadEncrypted(storage=globalThis.localStorage){try{const raw=storage.getItem?storage.getItem(STORAGE_KEY):storage.get(STORAGE_KEY);if(!raw)return null;const value=JSON.parse(raw);return value&&value.type==='testcode-chat-local'&&value.version===1?value:null}catch(_){return null}}
function saveEncrypted(envelope,storage=globalThis.localStorage){const raw=JSON.stringify(envelope);if(storage.setItem)storage.setItem(STORAGE_KEY,raw);else storage.set(STORAGE_KEY,raw);return envelope}
function clearEncrypted(storage=globalThis.localStorage){if(storage.removeItem)storage.removeItem(STORAGE_KEY);else storage.delete(STORAGE_KEY)}
function createConversation(state,id,now=new Date().toISOString()){const next=normalizeState(state),conversation={id:String(id||''),title:'新しいチャット',createdAt:String(now),updatedAt:String(now),messages:[]};if(!conversation.id)throw new Error('conversation id required');next.conversations=[conversation,...next.conversations.filter(c=>c.id!==conversation.id)];next.activeConversationId=conversation.id;return{state:next,conversation:clone(conversation)}}
function appendMessage(state,conversationId,message){const next=normalizeState(state),normalized=normalizeMessage(message);if(!normalized)return next;const target=next.conversations.find(c=>c.id===conversationId);if(!target)return next;target.messages.push(normalized);target.updatedAt=normalized.createdAt||new Date().toISOString();if(target.title==='新しいチャット'&&normalized.role==='user'&&normalized.content.trim())target.title=normalized.content.trim().replace(/\s+/g,' ').slice(0,32);return next}
function deleteConversation(state,conversationId){const next=normalizeState(state);next.conversations=next.conversations.filter(c=>c.id!==conversationId);if(next.activeConversationId===conversationId)next.activeConversationId=next.conversations[0]?.id||null;return next}
function replaceConversation(state,conversation){const next=normalizeState(state),normalized=normalizeConversation(conversation);if(!normalized)return next;const index=next.conversations.findIndex(c=>c.id===normalized.id);if(index>=0)next.conversations[index]=normalized;else next.conversations.unshift(normalized);return next}
const api={STORAGE_KEY,createDefaultState,normalizeState,encryptState,decryptState,loadEncrypted,saveEncrypted,clearEncrypted,createConversation,appendMessage,deleteConversation,replaceConversation};
if(typeof window!=='undefined')window.ChatStore=api;
if(typeof module!=='undefined')module.exports=api;
})();
