(()=>{
'use strict';
const $=(id)=>document.getElementById(id);
const DATA_KEYS=MangaVaultPayload.DATA_KEYS;
const OVERRIDE_KEY=MangaHomeLayout.PROFILE_OVERRIDE_KEY;
const registry=MangaHomeCards.createRegistry();
MangaHomeLocalCards.registerLocalCards(registry);
const ui={shell:$('homeShell'),grid:$('homeGrid'),edit:$('homeEditBtn'),editPanel:$('homeEditPanel'),catalog:$('homeCardCatalog'),reset:$('homeResetBtn'),profile:$('homeProfileSelect'),profileLabel:$('homeProfileLabel'),account:$('homeAccount'),status:$('homeStatus'),settings:$('homeSettingsPanel'),settingsTitle:$('homeSettingsTitle'),settingsBody:$('homeSettingsBody'),settingsClose:$('homeSettingsCloseBtn'),gate:$('vaultGateHost'),gateAccount:$('vaultAccount'),gateInput:$('vaultInputPanel'),gateStatus:$('vaultGateStatus'),passphrase:$('vaultPassphrase'),recovery:$('recoveryKey'),unlock:$('passphraseUnlockBtn'),passkeyUnlock:$('passkeyUnlockBtn'),create:$('createVaultBtn'),passkeyRegister:$('passkeyRegisterBtn'),gateLogout:$('gateLogoutBtn'),recoveryPanel:$('recoveryPanel'),recoveryCode:$('recoveryCode'),copyRecovery:$('copyRecoveryBtn'),recoveryContinue:$('recoveryContinueBtn'),logout:$('homeLogoutBtn')};
const session=MangaVault.loadSession();
if(!session||!session.user){location.replace('index.html');return;}
ui.account.textContent=session.user.email||'';ui.gateAccount.textContent=session.user.email||'';
let editing=false,draggedCardId=null,saveTimer=null,saveRunning=false,saveDirty=false,homeState=null,currentProfile='mobile',gateBusy=false;
function readJson(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||'null');return value==null?fallback:value}catch(_){return fallback}}
function setStatus(text,error=false){ui.status.textContent=text||'';ui.status.classList.toggle('isError',!!error)}
function gateStatus(text){ui.gateStatus.textContent=text||''}
function overrideValue(){const value=localStorage.getItem(OVERRIDE_KEY);return MangaHomeLayout.PROFILE_NAMES.includes(value)?value:null}
function resolveProfile(){return MangaHomeLayout.resolveProfile({width:innerWidth,maxTouchPoints:navigator.maxTouchPoints||0,override:overrideValue()})}
function loadHome(){homeState=MangaHomeLayout.normalizeHome(readJson(DATA_KEYS.home,null));localStorage.setItem(DATA_KEYS.home,JSON.stringify(homeState));return homeState}
function context(){const features=window.MangaReaderFeatures||{};return{profile:currentProfile,study:window.StudyData?StudyData.load():readJson(DATA_KEYS.study,{}),items:readJson(DATA_KEYS.items,[]),features,localReaderEnabled:!!features.localReader,navigate(href){location.href=href},requestRender(){renderDashboard()}}}
function scheduleCloudSave(){clearTimeout(saveTimer);saveTimer=setTimeout(flushCloudSave,750)}
async function flushCloudSave(){if(saveRunning){saveDirty=true;return}saveRunning=true;saveDirty=false;try{await MangaVault.savePayload(MangaVaultPayload.buildFromLocalStorage());setStatus('ホームを同期しました')}catch(error){setStatus(error&&error.message?error.message:'ホームを同期できませんでした',true)}finally{saveRunning=false;if(saveDirty)scheduleCloudSave()}}
function persistHome(next){homeState=MangaHomeLayout.normalizeHome(next);localStorage.setItem(DATA_KEYS.home,JSON.stringify(homeState));renderDashboard();scheduleCloudSave()}
function cardsForProfile(){return homeState.layouts[currentProfile].cards}
function makeButton(label,handler){const button=document.createElement('button');button.type='button';button.textContent=label;button.addEventListener('click',(event)=>{event.stopPropagation();handler(event)});return button}
function makeSizeSelect(instance,definition){const select=document.createElement('select');select.setAttribute('aria-label','カードサイズ');for(const size of definition.allowedSizes){const option=document.createElement('option');option.value=size;option.textContent=size==='small'?'小':size==='large'?'大':'中';option.selected=size===instance.size;select.appendChild(option)}select.addEventListener('click',(event)=>event.stopPropagation());select.addEventListener('change',()=>persistHome(MangaHomeLayout.resizeCard(homeState,currentProfile,instance.id,select.value)));return select}
function openSettings(instance,definition){ui.settings.hidden=false;ui.settingsTitle.textContent=definition.title+' の設定';ui.settingsBody.replaceChildren();registry.renderSettings({instance,host:ui.settingsBody,context:context(),updateSettings:(settings)=>persistHome(MangaHomeLayout.updateCardSettings(homeState,currentProfile,instance.id,settings))})}
function editControls(instance,index,definition){const box=document.createElement('div');box.className='homeEditControls';const up=makeButton('上へ',()=>{if(index>0)persistHome(MangaHomeLayout.moveCard(homeState,currentProfile,instance.id,index-1))});up.disabled=index===0;box.appendChild(up);const down=makeButton('下へ',()=>{if(index<cardsForProfile().length-1)persistHome(MangaHomeLayout.moveCard(homeState,currentProfile,instance.id,index+1))});down.disabled=index>=cardsForProfile().length-1;box.appendChild(down);box.appendChild(makeSizeSelect(instance,definition));box.appendChild(makeButton('設定',()=>openSettings(instance,definition)));box.appendChild(makeButton('削除',()=>persistHome(MangaHomeLayout.removeCard(homeState,currentProfile,instance.id))));return box}
function cardElement(instance,index){const definition=registry.get(instance.type);const section=document.createElement('article');section.className='homeCard'+(editing?' isEditing':'');section.dataset.cardId=instance.id;section.dataset.size=instance.size;const head=document.createElement('div');head.className='homeCardHeader';const title=document.createElement('h2');title.textContent=definition?definition.title:instance.type;head.appendChild(title);if(editing&&definition)head.appendChild(editControls(instance,index,definition));section.appendChild(head);const body=document.createElement('div');body.className='homeCardBody';section.appendChild(body);registry.render({instance,host:body,context:context()});if(editing){section.draggable=true;section.addEventListener('dragstart',()=>{draggedCardId=instance.id;section.classList.add('dragging')});section.addEventListener('dragend',()=>{draggedCardId=null;section.classList.remove('dragging')});section.addEventListener('dragover',(event)=>event.preventDefault());section.addEventListener('drop',(event)=>{event.preventDefault();if(!draggedCardId||draggedCardId===instance.id)return;const target=cardsForProfile().findIndex((card)=>card.id===instance.id);persistHome(MangaHomeLayout.moveCard(homeState,currentProfile,draggedCardId,target))})}return section}
function renderCatalog(){ui.catalog.replaceChildren();const present=new Set(cardsForProfile().map((card)=>card.type));const available=registry.list().filter((definition)=>!present.has(definition.type));if(!available.length){const text=document.createElement('span');text.className='homeCardMeta';text.textContent='追加できるカードはありません';ui.catalog.appendChild(text);return}for(const definition of available){const button=document.createElement('button');button.type='button';button.className='catalogBtn';button.textContent='＋ '+definition.title;button.addEventListener('click',()=>persistHome(MangaHomeLayout.addCard(homeState,currentProfile,{id:definition.type,type:definition.type,size:definition.allowedSizes.includes('medium')?'medium':definition.allowedSizes[0],settings:{}})));ui.catalog.appendChild(button)}}
function renderDashboard(){if(!homeState)loadHome();currentProfile=resolveProfile();ui.profileLabel.textContent=currentProfile==='mobile'?'スマホ用':currentProfile==='tablet'?'タブレット用':'PC用';ui.profile.value=overrideValue()||'auto';ui.grid.replaceChildren();const cards=cardsForProfile();if(!cards.length){const empty=document.createElement('div');empty.className='emptyHome';empty.textContent=editing?'カードを追加してHomeを作成できます':'表示するカードがありません。「ホームを編集」から追加できます。';ui.grid.appendChild(empty)}else cards.forEach((instance,index)=>ui.grid.appendChild(cardElement(instance,index)));ui.editPanel.hidden=!editing;if(editing)renderCatalog();ui.edit.textContent=editing?'編集完了':'ホームを編集'}
function showDashboard(){ui.gate.hidden=true;ui.shell.hidden=false;ui.status.hidden=false;ui.grid.hidden=false;ui.editPanel.hidden=!editing;ui.recoveryPanel.hidden=true;ui.recoveryCode.textContent='';loadHome();renderDashboard();document.documentElement.classList.remove('auth-pending')}
function validateGateInput({allowRecovery=true}={}){const passphrase=ui.passphrase.value,recovery=allowRecovery?ui.recovery.value.trim():'';if(!recovery&&passphrase.length<12){gateStatus('パスフレーズは12文字以上で入力してください。');return null}return{passphrase,recovery}}
const gate=MangaVaultGate.createController({vaultApi:MangaVault,payloadApi:MangaVaultPayload});
async function refreshVaultState(){try{const record=await MangaVault.withSession((token,user)=>MangaVault.fetchRecordForUi(token,user));const exists=!!record;ui.unlock.hidden=!exists;ui.passkeyUnlock.hidden=!exists;ui.passkeyRegister.hidden=!exists;ui.create.hidden=exists;if(!exists)gateStatus('保管庫はまだ作成されていません。')}catch(error){gateStatus(error&&error.message?error.message:'保管庫の状態を確認できませんでした。')}}
function displayRecovery(result){ui.gateInput.hidden=true;ui.recoveryPanel.hidden=false;ui.recoveryCode.textContent=result.recoveryCode||'';gateStatus('復旧キーを安全な場所へ保存してください。')}
async function unlockVault(){const input=validateGateInput();if(!input||gateBusy)return;gateBusy=true;gateStatus('保管庫を開いています…');try{const result=await gate.unlock(input);ui.passphrase.value='';ui.recovery.value='';if(result&&result.created)displayRecovery(result);else showDashboard()}catch(error){gateStatus(error&&error.message?error.message:'保管庫を開けませんでした。')}finally{gateBusy=false}}
async function unlockPasskey(){if(gateBusy)return;gateBusy=true;gateStatus('パスキーを確認しています…');try{await gate.unlockWithPasskey();showDashboard()}catch(error){gateStatus(error&&error.message?error.message:'パスキーで開けませんでした。')}finally{gateBusy=false}}
async function createVault(){const input=validateGateInput({allowRecovery:false});if(!input||gateBusy)return;gateBusy=true;gateStatus('保管庫を作成しています…');try{const result=await gate.create(input.passphrase);ui.passphrase.value='';displayRecovery(result)}catch(error){gateStatus(error&&error.message?error.message:'保管庫を作成できませんでした。')}finally{gateBusy=false}}
async function registerPasskey(){const input=validateGateInput({allowRecovery:false});if(!input||gateBusy)return;gateBusy=true;gateStatus('パスキーを登録しています…');try{await gate.registerPasskey(input.passphrase);ui.passphrase.value='';gateStatus('パスキーを登録しました。')}catch(error){gateStatus(error&&error.message?error.message:'パスキーを登録できませんでした。')}finally{gateBusy=false}}
async function logout(){if(!confirm('ログアウトしますか？'))return;try{await MangaVault.withSession((token)=>MangaVault.api('/auth/v1/logout',{method:'POST',token}))}catch(_){}MangaVault.clearActive();MangaVault.saveSession(null);localStorage.removeItem(MangaVault.META_KEY);MangaVaultPayload.clearDeviceData();for(const key of ['mangaReaderLastUrl','mangaReaderSavedUrls','mangaReaderGithubSync','mangaReaderVaultSyncMeta'])localStorage.removeItem(key);location.replace('index.html')}
function showVaultGate(){ui.shell.hidden=true;ui.grid.hidden=true;ui.editPanel.hidden=true;ui.settings.hidden=true;ui.status.hidden=true;ui.gate.hidden=false;ui.gateInput.hidden=false;ui.recoveryPanel.hidden=true;document.documentElement.classList.remove('auth-pending');refreshVaultState()}
ui.edit.addEventListener('click',()=>{editing=!editing;ui.settings.hidden=true;renderDashboard()});ui.profile.addEventListener('change',()=>{if(ui.profile.value==='auto')localStorage.removeItem(OVERRIDE_KEY);else localStorage.setItem(OVERRIDE_KEY,ui.profile.value);renderDashboard()});ui.reset.addEventListener('click',()=>{if(confirm('現在のレイアウトを初期状態に戻しますか？'))persistHome(MangaHomeLayout.resetProfile(homeState,currentProfile))});ui.settingsClose.addEventListener('click',()=>{ui.settings.hidden=true});ui.unlock.addEventListener('click',unlockVault);ui.passkeyUnlock.addEventListener('click',unlockPasskey);ui.create.addEventListener('click',createVault);ui.passkeyRegister.addEventListener('click',registerPasskey);ui.copyRecovery.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(ui.recoveryCode.textContent)}catch(_){}});ui.recoveryContinue.addEventListener('click',showDashboard);ui.gateLogout.addEventListener('click',logout);ui.logout.addEventListener('click',logout);window.addEventListener('resize',()=>{if(!overrideValue()&&!ui.shell.hidden)renderDashboard()});window.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&saveTimer){clearTimeout(saveTimer);saveTimer=null;flushCloudSave()}});
if(MangaVault.loadActive())showDashboard();else showVaultGate();
})();
