const StudyDataRef = typeof module !== 'undefined' && module.exports
  ? require('./study-data.js')
  : (typeof window !== 'undefined' ? window.StudyData : null);

const MAX_APPLIED_OPERATION_IDS = 4000;
const SUPPORTED_OPERATION_TYPES = new Set(['definition.upserted', 'definition.deleted', 'genre.upserted', 'attempt.upserted', 'preference.changed']);
const clone = (value) => (typeof structuredClone === 'function' ? structuredClone(value) : JSON.parse(JSON.stringify(value)));
function normalizeStudy(value){return StudyDataRef&&typeof StudyDataRef.normalizeStudy==='function'?StudyDataRef.normalizeStudy(value):clone(value||{})}
function createOperation(type,payload,options={}){if(!SUPPORTED_OPERATION_TYPES.has(type))throw new Error(`unsupported study operation: ${type}`);const id=options.id||(StudyDataRef&&StudyDataRef.createId?StudyDataRef.createId():`op-${Date.now()}-${Math.random()}`);return{id,type,payload:clone(payload||{}),occurredAt:options.occurredAt||new Date().toISOString()}}
function sameFinalGrading(a,b){return JSON.stringify(a&&a.grading)===JSON.stringify(b&&b.grading)}
function rememberAppliedId(study,id){const ids=Array.isArray(study.appliedOperationIds)?study.appliedOperationIds.filter(x=>x!==id):[];ids.push(id);study.appliedOperationIds=ids.slice(Math.max(0,ids.length-MAX_APPLIED_OPERATION_IDS));return study}
function applyAttempt(study,incoming,options){if(!incoming||!incoming.id)throw new Error('attempt.upserted requires attempt.id');const attempts=Array.isArray(study.recentAttempts)?study.recentAttempts.slice():[],index=attempts.findIndex(x=>x&&x.id===incoming.id),existing=index>=0?attempts[index]:null,incomingFinal=incoming.grading&&incoming.grading.status==='final',existingFinal=existing&&existing.grading&&existing.grading.status==='final';let reduce=false;if(existingFinal&&incomingFinal){if(!sameFinalGrading(existing,incoming))throw new Error('conflicting final grading')}else if(!existingFinal){if(index>=0)attempts[index]=clone(incoming);else attempts.push(clone(incoming));reduce=incomingFinal}let next={...study,recentAttempts:attempts};if(reduce&&typeof options.reduceFinalAttempt==='function')next=options.reduceFinalAttempt(next,clone(incoming))||next;return next}
function applyOperation(study,operation,options={}){if(!operation||!operation.id||!SUPPORTED_OPERATION_TYPES.has(operation.type))throw new Error('invalid study operation');let next=normalizeStudy(clone(study));if(next.appliedOperationIds.includes(operation.id))return next;if(operation.type==='definition.upserted'){const d=operation.payload&&operation.payload.definition;if(!d||!d.id)throw new Error('definition.upserted requires definition.id');const list=next.definitions.slice(),i=list.findIndex(x=>x&&x.id===d.id);if(i>=0)list[i]=clone(d);else list.push(clone(d));next.definitions=list}else if(operation.type==='definition.deleted'){const id=operation.payload&&operation.payload.definitionId;if(!id)throw new Error('definition.deleted requires definitionId');next.definitions=next.definitions.filter(x=>x&&x.id!==id);const p={...next.progress};delete p[id];next.progress=p;next.pendingGradings=next.pendingGradings.filter(attemptId=>{const a=next.recentAttempts.find(x=>x&&x.id===attemptId);return!a||a.definitionId!==id})}else if(operation.type==='genre.upserted'){const g=operation.payload&&operation.payload.genre;if(!g||!g.id||!g.subjectId||!g.name)throw new Error('genre.upserted requires genre');const list=next.genres.slice(),i=list.findIndex(x=>x&&x.id===g.id);if(i>=0)list[i]=clone(g);else list.push(clone(g));next.genres=list}else if(operation.type==='preference.changed')next.preferences={...next.preferences,...(operation.payload||{})};else if(operation.type==='attempt.upserted')next=applyAttempt(next,operation.payload&&operation.payload.attempt,options);return rememberAppliedId(next,operation.id)}
function queueOperation(study,operation){const next=normalizeStudy(clone(study));if(!next.pendingSyncOps.some(x=>x&&x.id===operation.id))next.pendingSyncOps.push(clone(operation));return next}
function rebaseStudy(remoteStudy,pendingOps,options={}){const ordered=(Array.isArray(pendingOps)?pendingOps:[]).map((operation,index)=>({operation,index})).sort((a,b)=>String(a.operation.occurredAt||'').localeCompare(String(b.operation.occurredAt||''))||a.index-b.index);return ordered.reduce((state,e)=>applyOperation(state,e.operation,options),normalizeStudy(clone(remoteStudy)))}
function canonicalize(value){if(Array.isArray(value))return value.map(canonicalize);if(!value||typeof value!=='object')return value;return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonicalize(value[k])]))}
function fingerprintNonStudy(payload){const source=payload&&typeof payload==='object'?payload:{},{study,...nonStudy}=source;return JSON.stringify(canonicalize(nonStudy))}
function storageGet(storage,key){return storage.getItem?storage.getItem(key):(storage.get(key)??null)}function storageSet(storage,key,value){if(storage.setItem)storage.setItem(key,value);else storage.set(key,value)}
function decodeB64url(value){const normalized=String(value||'').replace(/-/g,'+').replace(/_/g,'/'),padded=normalized+'='.repeat((4-normalized.length%4)%4);if(typeof atob==='function')return Uint8Array.from(atob(padded),c=>c.charCodeAt(0));if(typeof Buffer!=='undefined')return Uint8Array.from(Buffer.from(padded,'base64'));throw new Error('base64 decoder unavailable')}
async function decryptRemoteEnvelope(vault,envelope,cryptoImpl=globalThis.crypto){const active=vault&&typeof vault.loadActive==='function'?vault.loadActive():null;if(!active||!active.rawKey)throw new Error('保管庫を開いてください。');if(!envelope||!envelope.data||!envelope.data.iv||!envelope.data.ciphertext)throw new Error('保管庫の形式が正しくありません。');if(!cryptoImpl||!cryptoImpl.subtle)throw new Error('このブラウザは暗号化機能に対応していません。');const key=await cryptoImpl.subtle.importKey('raw',active.rawKey,{name:'AES-GCM'},false,['decrypt']),plain=await cryptoImpl.subtle.decrypt({name:'AES-GCM',iv:decodeB64url(envelope.data.iv)},key,decodeB64url(envelope.data.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
async function reloadVaultPayload(vault,options={}){if(!vault||typeof vault.withSession!=='function'||typeof vault.fetchRecordForUi!=='function')throw new Error('vault reload API is required');const storage=options.storage||globalThis.localStorage,decryptEnvelope=options.decryptEnvelope||(envelope=>decryptRemoteEnvelope(vault,envelope,options.cryptoImpl));return vault.withSession(async(token,user)=>{const record=await vault.fetchRecordForUi(token,user);if(!record)return null;if(record.legacyRevision)throw new Error('Supabaseのrevision migrationが未適用です。supabase-schema.sqlをSQL Editorで実行してから同期してください。');const payload=await decryptEnvelope(record.payload),revision=record.revision||1,updatedAt=record.updated_at,metaKey=vault.META_KEY||'mangaReaderSupabaseSyncMeta';let meta={};try{meta=JSON.parse(storageGet(storage,metaKey)||'{}')||{}}catch(_){meta={}}meta[user.id]={revision,updatedAt};storageSet(storage,metaKey,JSON.stringify(meta));return{payload,revision,updatedAt}})}
function createController({vault,payloadApi,storage,reduceFinalAttempt}={}){if(!vault||typeof vault.savePayload!=='function')throw new Error('vault.savePayload is required');if(!payloadApi||typeof payloadApi.buildFromLocalStorage!=='function'||typeof payloadApi.applyToLocalStorage!=='function')throw new Error('payloadApi is required');let baseline=null,status='idle';const build=()=>payloadApi.buildFromLocalStorage(storage),applyPayload=p=>payloadApi.applyToLocalStorage(p,storage),markBase=p=>baseline=fingerprintNonStudy(p||build()),getStatus=()=>status;async function syncNow(){const current=build(),study=normalizeStudy(current.study),pending=study.pendingSyncOps.slice();if(!pending.length){status='idle';if(baseline==null)markBase(current);return{status:'idle'}}if(baseline==null)markBase(current);const ids=new Set(pending.map(x=>x.id)),without={...study,pendingSyncOps:study.pendingSyncOps.filter(x=>!ids.has(x.id))},toSave={...current,study:without};status='syncing';try{await vault.savePayload(toSave);applyPayload(toSave);markBase(toSave);status='synced';return{status:'synced'}}catch(error){if(!String(error&&error.message||'').includes('別の端末で更新されています')){status='error';throw error}if(fingerprintNonStudy(current)!==baseline){status='conflict';return{status:'conflict',reason:'non-study-local-change'}}const remote=typeof vault.reloadPayload==='function'?await vault.reloadPayload():await reloadVaultPayload(vault,{storage});if(!remote||!remote.payload){status='conflict';return{status:'conflict',reason:'remote-missing'}}const rebased=rebaseStudy(remote.payload.study,pending,{reduceFinalAttempt});rebased.pendingSyncOps=rebased.pendingSyncOps.filter(x=>!ids.has(x.id));const payload={...remote.payload,study:rebased};await vault.savePayload(payload);applyPayload(payload);markBase(payload);status='synced-after-rebase';return{status:'synced-after-rebase'}}}return{syncNow,getStatus,markBase}}
const api={MAX_APPLIED_OPERATION_IDS,createOperation,applyOperation,queueOperation,rebaseStudy,fingerprintNonStudy,reloadVaultPayload,createController};if(typeof window!=='undefined')window.StudySync=api;if(typeof module!=='undefined')module.exports=api;
