const DATA_KEYS={folders:'mangaReaderSavedFolders',items:'mangaReaderSavedItems',videos:'mangaReaderVideos',videoFolders:'mangaReaderVideoFolders',videoMeta:'mangaReaderVideoMeta',videoMarkers:'mangaReaderVideoMarkers',videoShortsState:'mangaReaderVideoShortsState',authorCards:'mangaReaderAuthorCards',mangaInfo:'mangaReaderInfoCache',toc:'mangaReaderToc',lastPages:'mangaReaderLastPage',theme:'mangaReaderTheme',dashboardVisibility:'mangaReaderDashboardVisibility',homeCards:'mangaReaderHomeCards',study:'mangaReaderStudy',indexSearchSettings:'mangaReaderIndexSearchSettings',roppoState:'mangaReaderRoppoState',statuteNotes:'mangaReaderStatuteNotes',profileAvatar:'mangaReaderProfileAvatar',driveGalleryEncrypted:'mangaReaderDriveGalleryEncrypted',gameSave:'mangaReaderCityDaysSave',syncTombstones:'mangaReaderVaultSyncTombstones'};
const defaultDashboardVisibility={continue:false,'recent-added':false,'recent-read':false,unread:false,random:false,favorites:false};
const defaultHomeCards=['bookshelf','roppo','index-search','study','quiz','links','egov','courts','moj-exam'];
const defaultIndexSearchSettings={matchModes:{exact:true,partial:true,and:true,fuzzy:true},activeKind:'all',selectedSubjects:[],selectedBookIds:[]};
const defaultMemoVisibility={requirements:true,effects:true,definitions:true,purpose:true};
const defaultRoppoState={schemaVersion:3,notes:{},favorites:[],recent:[],preferences:{selectedGroup:'constitutional-law',selectedLawId:'321CONSTITUTION',memoMode:'view',memoVisibility:{...defaultMemoVisibility}}};
const roppoGroups={'constitutional-law':['321CONSTITUTION'],'civil-law':['129AC0000000089'],'criminal-law':['140AC0000000045'],'civil-procedure':['408AC0000000109'],'criminal-procedure':['323AC0000000131'],'administrative-law':['405AC0000000088','337AC0000000139','426AC0000000068','322AC0000000125'],'company-law':['417AC0000000086']};const roppoLawIds=new Set(Object.values(roppoGroups).flat());
const defaultStudySubjects=[{id:'constitutional-law',name:'憲法'},{id:'administrative-law',name:'行政法'},{id:'civil-law',name:'民法'},{id:'commercial-law',name:'商法'},{id:'civil-procedure',name:'民事訴訟法'},{id:'criminal-law',name:'刑法'},{id:'criminal-procedure',name:'刑事訴訟法'},{id:'labor-law',name:'労働法'}];
const createEmptyStudy=()=>({schemaVersion:1,subjects:defaultStudySubjects.map((item)=>({...item})),genres:[],definitions:[],arguments:[],argumentDrafts:{},argumentProgress:{},recentAttempts:[],progress:{},pendingGradings:[],pendingSyncOps:[],appliedOperationIds:[],gamification:{xp:0,streak:0,lastStudyDate:null},preferences:{autoSpeak:false}});
const cloneIndexSearchSettings=()=>({matchModes:{...defaultIndexSearchSettings.matchModes},activeKind:'all',selectedSubjects:[],selectedBookIds:[]});const cloneRoppoState=()=>({schemaVersion:3,notes:{},favorites:[],recent:[],preferences:{selectedGroup:defaultRoppoState.preferences.selectedGroup,selectedLawId:defaultRoppoState.preferences.selectedLawId,memoMode:'view',memoVisibility:{...defaultMemoVisibility}}});
const defaults={folders:[],items:[],videos:[],videoFolders:[],videoMeta:{},videoMarkers:{},videoShortsState:{schemaVersion:1,queue:[],currentIndex:0,currentTime:0,knownVideoIds:[],generation:0,updatedAt:0,revision:0},authorCards:[],mangaInfo:{},toc:{},lastPages:{},theme:'dark',dashboardVisibility:{mobile:{...defaultDashboardVisibility},desktop:{...defaultDashboardVisibility}},homeCards:defaultHomeCards.slice(),study:createEmptyStudy(),indexSearchSettings:cloneIndexSearchSettings(),roppoState:cloneRoppoState(),statuteNotes:{},profileAvatar:'',driveGalleryEncrypted:null,gameSave:null,vaultSyncTombstones:[]};
const isObject=(value)=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const SENSITIVE_UNKNOWN_KEY=/(?:password|passphrase|secret|credential|access[_-]?token|refresh[_-]?token|api[_-]?key|private[_-]?key|vault[_-]?key)/i;
function preserveUnknownShape(value){if(Array.isArray(value))return value.map(preserveUnknownShape);if(!value||typeof value!=='object')return value;const result={};Object.entries(value).forEach(([key,child])=>{if(!SENSITIVE_UNKNOWN_KEY.test(key))result[key]=preserveUnknownShape(child)});return result}
const normalizeDashboardProfile=(value)=>{const source=isObject(value),result={...preserveUnknownShape(source),...defaultDashboardVisibility};Object.keys(defaultDashboardVisibility).forEach((key)=>{if(typeof source[key]==='boolean')result[key]=source[key]});return result};const normalizeDashboardVisibility=(value)=>{const source=isObject(value);return source.mobile&&source.desktop?{...preserveUnknownShape(source),mobile:normalizeDashboardProfile(source.mobile),desktop:normalizeDashboardProfile(source.desktop)}:{...preserveUnknownShape(source),mobile:normalizeDashboardProfile(),desktop:normalizeDashboardProfile()}};const normalizeHomeCards=(value)=>Array.isArray(value)?value.map((id)=>String(id||'')).filter(Boolean):defaultHomeCards.slice();const normalizeStringArray=(value)=>Array.isArray(value)?value.map((item)=>String(item??'').trim()).filter(Boolean):[];
const VIDEO_MARKER_ICONS=new Set(['water','triangle','toilet']);
const LEGACY_MARKER_ICONS={water:'water','water-splash':'water','水しぶき':'water',triangle:'triangle','upward-triangle':'triangle','上向き三角':'triangle',toilet:'toilet','toilet-mark':'toilet','トイレマーク':'toilet','便器':'toilet'};
function normalizeVideoMarkers(value){const result={};Object.entries(isObject(value)).forEach(([rawId,rawMarkers])=>{const id=String(rawId||'').trim();if(!id||!Array.isArray(rawMarkers))return;const markers=[];rawMarkers.forEach((raw)=>{const marker=isObject(raw),seconds=Number(marker.seconds);if(!Number.isFinite(seconds)||seconds<0)return;const requested=String(marker.icon||'').trim(),label=String(marker.label||'').trim().toLocaleLowerCase('ja'),icon=VIDEO_MARKER_ICONS.has(requested)?requested:(LEGACY_MARKER_ICONS[requested]||LEGACY_MARKER_ICONS[label]||'triangle');const normalizedMarker={...preserveUnknownShape(marker),seconds,icon};delete normalizedMarker.label;markers.push(normalizedMarker)});if(markers.length)result[id]=markers});return result}
const defaultVideoShortsState={schemaVersion:1,queue:[],currentIndex:0,currentTime:0,knownVideoIds:[],generation:0,updatedAt:0,revision:0};
const safeInteger=(value)=>Number.isSafeInteger(Number(value))&&Number(value)>=0?Number(value):0;
function normalizeVideoShortsState(value){const source=isObject(value),entryTypes=new Set(['marker','random-short','overflow-landscape','overflow-long']);const queue=(Array.isArray(source.queue)?source.queue:[]).map((raw)=>{const entry=isObject(raw),videoId=String(entry.videoId||'').trim(),startSeconds=Number(entry.startSeconds),endSeconds=Number(entry.endSeconds),tier=Number(entry.tier);if(!videoId||!Number.isFinite(startSeconds)||startSeconds<0||!Number.isFinite(endSeconds)||endSeconds<startSeconds||!entryTypes.has(entry.entryType)||!Number.isSafeInteger(tier)||tier<1||tier>5)return null;return{...preserveUnknownShape(entry),videoId,startSeconds,endSeconds,entryType:entry.entryType,tier,generation:safeInteger(entry.generation)}}).filter(Boolean);const currentIndex=queue.length?Math.min(safeInteger(source.currentIndex),queue.length-1):0,active=queue[currentIndex],rawTime=Number(source.currentTime),currentTime=queue.length&&Number.isFinite(rawTime)&&rawTime>=0?Math.max(active.startSeconds,Math.min(rawTime,active.endSeconds)):0;return{...preserveUnknownShape(source),schemaVersion:1,queue,currentIndex,currentTime,knownVideoIds:normalizeStringArray(source.knownVideoIds).filter((id,index,list)=>list.indexOf(id)===index),generation:safeInteger(source.generation),updatedAt:Number.isFinite(Number(source.updatedAt))&&Number(source.updatedAt)>=0?Number(source.updatedAt):0,revision:safeInteger(source.revision)}}
function normalizeIndexSearchSettings(value){const source=isObject(value),modes=isObject(source.matchModes),allowedKinds=new Set(['all','matter','case','statute']);return{...preserveUnknownShape(source),matchModes:{...preserveUnknownShape(modes),exact:modes.exact===undefined?true:Boolean(modes.exact),partial:modes.partial===undefined?true:Boolean(modes.partial),and:modes.and===undefined?true:Boolean(modes.and),fuzzy:modes.fuzzy===undefined?true:Boolean(modes.fuzzy)},activeKind:allowedKinds.has(source.activeKind)?source.activeKind:'all',selectedSubjects:normalizeStringArray(source.selectedSubjects),selectedBookIds:normalizeStringArray(source.selectedBookIds)}}
function normalizeMemoVisibility(value){const source=isObject(value),result={...preserveUnknownShape(source)};Object.keys(defaultMemoVisibility).forEach((key)=>{result[key]=typeof source[key]==='boolean'?source[key]:true});return result}
function normalizeRoppoState(value){const source=isObject(value),notes={};Object.entries(isObject(source.notes)).forEach(([key,note])=>{const n=isObject(note);if(!/^.+\|.+\|P_[^|]+$/.test(key))return;const structured={requirements:typeof n.requirements==='string'?n.requirements:'',effects:typeof n.effects==='string'?n.effects:'',definitions:typeof n.definitions==='string'?n.definitions:'',purpose:typeof n.purpose==='string'?n.purpose:''};if(!Object.values(structured).some((v)=>v.trim()))return;notes[key]={...preserveUnknownShape(n),...structured,updatedAt:typeof n.updatedAt==='string'?n.updatedAt:''}});const seenFavorites=new Set(),favorites=[];(Array.isArray(source.favorites)?source.favorites:[]).forEach((key)=>{if(typeof key!=='string'||!key.includes('|')||seenFavorites.has(key))return;seenFavorites.add(key);favorites.push(key)});const recent=[],seenRecent=new Set();(Array.isArray(source.recent)?source.recent:[]).forEach((entry)=>{const item=isObject(entry),lawId=String(item.lawId||'').trim(),articleKey=String(item.articleKey||'').trim(),key=`${lawId}|${articleKey}`;if(!roppoLawIds.has(lawId)||!articleKey||seenRecent.has(key))return;seenRecent.add(key);recent.push({lawId,articleKey,viewedAt:typeof item.viewedAt==='string'?item.viewedAt:''})});const prefs=isObject(source.preferences),selectedGroup=roppoGroups[prefs.selectedGroup]?prefs.selectedGroup:defaultRoppoState.preferences.selectedGroup,selectedLawId=roppoGroups[selectedGroup].includes(prefs.selectedLawId)?prefs.selectedLawId:roppoGroups[selectedGroup][0],memoMode=prefs.memoMode==='edit'?'edit':'view';return{...preserveUnknownShape(source),schemaVersion:3,notes,favorites,recent:recent.slice(0,50),preferences:{...preserveUnknownShape(prefs),selectedGroup,selectedLawId,memoMode,memoVisibility:normalizeMemoVisibility(prefs.memoVisibility)}}}
function normalizeDriveGalleryEncrypted(value){if(!value||typeof value!=='object'||Array.isArray(value))return null;if(value.type!=='testcode-drive-gallery-settings'||value.version!==1||typeof value.iv!=='string'||typeof value.ciphertext!=='string'||!/^[A-Za-z0-9_-]{16}$/.test(value.iv)||!/^[A-Za-z0-9_-]{22,2100000}$/.test(value.ciphertext))return null;return{type:value.type,version:1,iv:value.iv,ciphertext:value.ciphertext}}
function normalizeProfileAvatar(value){return typeof value==='string'&&value.length<=100000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(value)?value:''}
function normalizeStatuteNotes(value){const result={};Object.entries(isObject(value)).forEach(([key,note])=>{if(!note||typeof note!=='object'||Array.isArray(note))return;const text=String(note.text??'').trim();if(!text)return;result[String(key).trim()]={...preserveUnknownShape(note),text,updatedAt:Number(note.updatedAt)>0?Number(note.updatedAt):Date.now(),tags:normalizeStringArray(note.tags)}});return result}
function normalizeStudyForVault(value){const x=isObject(value),base=createEmptyStudy();return{...preserveUnknownShape(x),schemaVersion:1,subjects:Array.isArray(x.subjects)&&x.subjects.length?x.subjects:base.subjects,genres:Array.isArray(x.genres)?x.genres:[],definitions:Array.isArray(x.definitions)?x.definitions:[],arguments:Array.isArray(x.arguments)?x.arguments:[],argumentDrafts:isObject(x.argumentDrafts),argumentProgress:isObject(x.argumentProgress),recentAttempts:Array.isArray(x.recentAttempts)?x.recentAttempts:[],progress:isObject(x.progress),pendingGradings:Array.isArray(x.pendingGradings)?x.pendingGradings:[],pendingSyncOps:Array.isArray(x.pendingSyncOps)?x.pendingSyncOps:[],appliedOperationIds:Array.isArray(x.appliedOperationIds)?x.appliedOperationIds:[],gamification:{...base.gamification,...preserveUnknownShape(isObject(x.gamification))},preferences:{...base.preferences,...preserveUnknownShape(isObject(x.preferences))}}}
function normalize(value){const x=value&&typeof value==='object'?value:{};return{...preserveUnknownShape(x),folders:Array.isArray(x.folders)?preserveUnknownShape(x.folders):[],items:Array.isArray(x.items)?preserveUnknownShape(x.items):[],videos:Array.isArray(x.videos)?preserveUnknownShape(x.videos):[],videoFolders:Array.isArray(x.videoFolders)?preserveUnknownShape(x.videoFolders):[],videoMeta:preserveUnknownShape(isObject(x.videoMeta)),videoMarkers:normalizeVideoMarkers(x.videoMarkers),videoShortsState:normalizeVideoShortsState(x.videoShortsState),authorCards:Array.isArray(x.authorCards)?preserveUnknownShape(x.authorCards):[],mangaInfo:preserveUnknownShape(isObject(x.mangaInfo)),toc:preserveUnknownShape(isObject(x.toc)),lastPages:preserveUnknownShape(isObject(x.lastPages)),theme:x.theme==='light'?'light':'dark',dashboardVisibility:normalizeDashboardVisibility(x.dashboardVisibility),homeCards:normalizeHomeCards(x.homeCards),study:normalizeStudyForVault(x.study),indexSearchSettings:normalizeIndexSearchSettings(x.indexSearchSettings),roppoState:normalizeRoppoState(x.roppoState),profileAvatar:normalizeProfileAvatar(x.profileAvatar),statuteNotes:normalizeStatuteNotes(x.statuteNotes),driveGalleryEncrypted:normalizeDriveGalleryEncrypted(x.driveGalleryEncrypted),gameSave:x.gameSave&&typeof x.gameSave==='object'&&!Array.isArray(x.gameSave)?preserveUnknownShape(x.gameSave):null,vaultSyncTombstones:normalizeStringArray(x.vaultSyncTombstones).filter((path)=>path.startsWith('/'))}}
function read(storage,key,fallback){try{const raw=rawValue(storage,key);return raw==null?fallback:JSON.parse(raw)}catch(_){return fallback}}function rawValue(storage,key){if(storage&&typeof storage.getItem==='function')return storage.getItem(key);if(storage&&typeof storage.get==='function')return storage.get(key)??null;if(storage&&typeof storage==='object')return Object.prototype.hasOwnProperty.call(storage,key)?storage[key]:null;return null}function setRaw(storage,key,value){if(storage&&typeof storage.setItem==='function')storage.setItem(key,value);else if(storage&&typeof storage.set==='function')storage.set(key,value);else if(storage&&typeof storage==='object')storage[key]=value;else throw new TypeError('保存領域を利用できません。')}function removeRaw(storage,key){if(storage&&typeof storage.removeItem==='function')storage.removeItem(key);else if(storage&&typeof storage.delete==='function')storage.delete(key);else if(storage&&typeof storage==='object')delete storage[key]}function write(storage,key,value){setRaw(storage,key,JSON.stringify(value))}function readTheme(storage){const raw=rawValue(storage,DATA_KEYS.theme);return String(raw??'').replace(/^"|"$/g,'').trim()==='light'?'light':'dark'}
function buildFromStorage(storage=globalThis.localStorage){return normalize({folders:read(storage,DATA_KEYS.folders,[]),items:read(storage,DATA_KEYS.items,[]),videos:read(storage,DATA_KEYS.videos,[]),videoFolders:read(storage,DATA_KEYS.videoFolders,[]),videoMeta:read(storage,DATA_KEYS.videoMeta,{}),videoMarkers:read(storage,DATA_KEYS.videoMarkers,{}),videoShortsState:read(storage,DATA_KEYS.videoShortsState,defaultVideoShortsState),authorCards:read(storage,DATA_KEYS.authorCards,[]),mangaInfo:read(storage,DATA_KEYS.mangaInfo,{}),toc:read(storage,DATA_KEYS.toc,{}),lastPages:read(storage,DATA_KEYS.lastPages,{}),theme:readTheme(storage),dashboardVisibility:read(storage,DATA_KEYS.dashboardVisibility,{}),homeCards:read(storage,DATA_KEYS.homeCards,defaultHomeCards),study:read(storage,DATA_KEYS.study,{}),indexSearchSettings:read(storage,DATA_KEYS.indexSearchSettings,defaultIndexSearchSettings),roppoState:read(storage,DATA_KEYS.roppoState,defaultRoppoState),statuteNotes:read(storage,DATA_KEYS.statuteNotes,{}),profileAvatar:rawValue(storage,DATA_KEYS.profileAvatar)||'',driveGalleryEncrypted:read(storage,DATA_KEYS.driveGalleryEncrypted,null),gameSave:read(storage,DATA_KEYS.gameSave,null),vaultSyncTombstones:read(storage,DATA_KEYS.syncTombstones,[])})}
function applyToStorage(payload,storage=globalThis.localStorage){const data=normalize(payload),snapshot=new Map(Object.values(DATA_KEYS).map((key)=>[key,rawValue(storage,key)]));try{Object.entries(DATA_KEYS).forEach(([name,key])=>{const value=name==='syncTombstones'?data.vaultSyncTombstones:data[name];name==='profileAvatar'?setRaw(storage,key,value):write(storage,key,value)});return data}catch(error){snapshot.forEach((value,key)=>{try{if(value==null)removeRaw(storage,key);else setRaw(storage,key,value)}catch(_){}});throw error}}function clearDeviceData(storage=globalThis.localStorage){Object.values(DATA_KEYS).forEach((key)=>{if(storage.removeItem)storage.removeItem(key);else storage.delete(key)})}

const MANUAL_VPN_IPS_KEY='testCode.manualVpnIps';
const MANUAL_NON_VPN_IPS_KEY='testCode.manualNonVpnIps';
const originalNormalize=normalize,originalBuildFromStorage=buildFromStorage,originalApplyToStorage=applyToStorage;
const normalizeWithManualIps=(value)=>{const result=originalNormalize(value),source=isObject(value);return{...result,manualVpnIps:normalizeStringArray(source.manualVpnIps),manualNonVpnIps:normalizeStringArray(source.manualNonVpnIps)}};
const buildWithManualIps=(storage=globalThis.localStorage)=>({...originalBuildFromStorage(storage),manualVpnIps:normalizeStringArray(read(storage,MANUAL_VPN_IPS_KEY,[])),manualNonVpnIps:normalizeStringArray(read(storage,MANUAL_NON_VPN_IPS_KEY,[]))});
const applyWithManualIps=(payload,storage=globalThis.localStorage)=>{const keys=[...Object.values(DATA_KEYS),MANUAL_VPN_IPS_KEY,MANUAL_NON_VPN_IPS_KEY],snapshot=new Map(keys.map((key)=>[key,rawValue(storage,key)]));try{const result=originalApplyToStorage(payload,storage),vpn=normalizeStringArray(payload&&payload.manualVpnIps),nonVpn=normalizeStringArray(payload&&payload.manualNonVpnIps);write(storage,MANUAL_VPN_IPS_KEY,vpn);write(storage,MANUAL_NON_VPN_IPS_KEY,nonVpn);return{...result,manualVpnIps:vpn,manualNonVpnIps:nonVpn}}catch(error){snapshot.forEach((value,key)=>{try{if(value==null)removeRaw(storage,key);else setRaw(storage,key,value)}catch(_){}});throw error}};
const clearWithManualIps=(storage=globalThis.localStorage)=>{clearDeviceData(storage);removeRaw(storage,MANUAL_VPN_IPS_KEY);removeRaw(storage,MANUAL_NON_VPN_IPS_KEY)};
function markSyncDeletion(path,storage=globalThis.localStorage){const value=String(path||'');if(!value.startsWith('/'))throw new TypeError('削除パスはJSON Pointer形式で指定してください。');const current=normalizeStringArray(read(storage,DATA_KEYS.syncTombstones,[]));if(!current.includes(value))current.push(value);write(storage,DATA_KEYS.syncTombstones,current);if(typeof window!=='undefined')window.MangaVault?.markLocalChangesPending?.();return current.length}
const api={DATA_KEYS,defaults,normalize:normalizeWithManualIps,normalizeVideoMarkers,normalizeVideoShortsState,buildFromLocalStorage:buildWithManualIps,applyToLocalStorage:applyWithManualIps,clearDeviceData:clearWithManualIps,markSyncDeletion,normalizeIndexSearchSettings,normalizeRoppoState,normalizeStatuteNotes};if(typeof window!=='undefined')window.MangaVaultPayload=api;if(typeof module!=='undefined')module.exports=api;
