import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const read=(name)=>fs.readFileSync(new URL(`../${name}`,import.meta.url),'utf8');

test('study page uses query history routing for old and definition quiz views',()=>{const source=read('study.html');for(const view of ['subjects','arguments','past-questions','review','progress','definitions','definition-editor','quiz','quiz-session'])assert.match(source,new RegExp(`['\\"]${view}['\\"]`));assert.match(source,/searchParams\.get\(['"]view['"]\)/);assert.match(source,/searchParams\.set\(['"]view['"],\s*normalized\)/);assert.match(source,/history\.pushState\(/);assert.match(source,/history\.replaceState\(/);assert.match(source,/addEventListener\(['"]popstate['"]/);assert.doesNotMatch(source,/<dialog\b/i)});
test('study page loads modular quiz system',()=>{const source=read('study.html');for(const file of ['vault-payload.js','study-data.js','study-sync.js','study-quiz.js','study-audio.js','study-ai.js','study-offline.js'])assert.match(source,new RegExp(file.replace('.','\\.')))});
test('study browser scripts can share one classic-script global scope',()=>{const context=vm.createContext({console});context.window=context;for(const file of ['vault-payload.js','study-data.js','study-sync.js','study-quiz.js','study-audio.js','study-ai.js','study-offline.js'])vm.runInContext(read(file),context,{filename:file});for(const name of ['MangaVaultPayload','StudyData','StudySync','StudyQuiz','StudyAudio','StudyAI','StudyOffline'])assert.ok(context[name],`${name} should be exported`)});
test('definition editor exposes editable AI structure and readings',()=>{const source=read('study.html');for(const id of ['definitionSubject','definitionGenre','definitionTitle','definitionModelText','definitionTitlePronunciation','definitionModelPronunciation','memoryUnitsEditor','clozeEditor','analyzeDefinitionBtn','regenerateReadingBtn','saveDefinitionBtn'])assert.match(source,new RegExp(`id=['\\"]${id}['\\"]`))});
test('quiz launcher feels like a focused lesson instead of a settings form',()=>{const source=read('study.html');assert.match(source,/今日のクイズを始めよう/);assert.match(source,/id=['"]startAutoQuiz['"]/);assert.match(source,/範囲・読み上げ設定/);assert.doesNotMatch(source,/おまかせで始める/);assert.doesNotMatch(source,/>\s*範囲を指定する\s*</)});
test('quiz session uses lesson-focused controls and clear give-up feedback',()=>{const source=read('study.html');assert.match(source,/思い出せない/);assert.match(source,/id=['"]quizProgressBar['"]/);assert.match(source,/id=['"]quizSpeakerBtn['"]/);assert.match(source,/lessonHero/);assert.match(source,/lessonFooter/);assert.match(source,/答えを確認/);assert.match(source,/あとでもう一度出ます/);assert.match(source,/この問題が答えられるようになっています/);assert.doesNotMatch(source,/>\s*Lv\.\d/);assert.doesNotMatch(source,/弱点穴埋め/);assert.doesNotMatch(source,/完全再現/);assert.doesNotMatch(source,/次回はこの.*穴埋め.*再登場/);assert.doesNotMatch(source,/復習期限と弱点から/);assert.doesNotMatch(source,/>\s*8\s*\/\s*10\s*</)});
test('navigation separates top-level tabs from hierarchical back navigation',()=>{const source=read('study.html');assert.match(source,/const TOP_LEVEL_VIEWS=\[['"]home['"],['"]subjects['"],['"]arguments['"],['"]past-questions['"],['"]review['"]\]/);assert.match(source,/id=['"]studyContextNav['"]/);assert.match(source,/id=['"]contextBackBtn['"]/);assert.match(source,/id=['"]contextNavTitle['"]/);assert.match(source,/TOP_LEVEL_VIEWS\.includes\(view\)/);assert.match(source,/contextNav\.hidden\s*=\s*topLevel\s*\|\|\s*view===['"]quiz-session['"]/);assert.match(source,/dock\.hidden\s*=\s*!topLevel/);assert.doesNotMatch(source,/class=['"]sectionBack['"]/);assert.doesNotMatch(source,/\sdata-back(?:\s|>)/)});
test('Liquid Glass navigation is readable, adaptive, and not dependent on SVG refraction',()=>{const source=read('study.html');for(const id of ['studyNavHome','studyNavSubjects','studyNavArguments','studyNavPastQuestions','studyNavReview'])assert.match(source,new RegExp(`id=['\\"]${id}['\\"]`));assert.match(source,/id=['"]studyBottomNav['"]/);assert.match(source,/--glass-surface:/);assert.match(source,/--glass-text:/);assert.match(source,/--glass-muted:/);assert.match(source,/html\[data-theme=['"]dark['"]\][^{]*\{[^}]*--glass-surface:/);assert.match(source,/\.studyNavBtn\{[^}]*font-size:\s*12px/);assert.match(source,/\.studyNavBtn\{[^}]*min-height:\s*52px/);assert.match(source,/backdrop-filter:\s*blur\(28px\)\s+saturate\(150%\)/);assert.match(source,/@supports not \(\(backdrop-filter:blur\(1px\)\) or \(-webkit-backdrop-filter:blur\(1px\)\)\)/);assert.match(source,/env\(safe-area-inset-bottom\)/);assert.match(source,/@media\(min-width:900px\)[\s\S]*#studyBottomNav\{[^}]*grid-template-columns:\s*1fr/);assert.match(source,/@media\(prefers-reduced-motion:reduce\)/);assert.doesNotMatch(source,/id=['"]liquidRefraction['"]/);assert.doesNotMatch(source,/pointermove[\s\S]*updateGlassLight/)});
test('auth guard remains present',()=>{const source=read('study.html');assert.match(source,/class=['"]auth-pending['"]/);assert.match(source,/supabase-config\.js/);assert.match(source,/vault-session\.js/);assert.match(source,/mangaReaderSupabaseSession/);assert.match(source,/MangaVault\.loadActive\(\)/);assert.match(source,/window\.location\.replace\(['"]sync\.html['"]\)/);assert.match(source,/window\.location\.replace\(['"]index\.html['"]\)/)});
test('reader still exposes judicial exam study entry',()=>{const source=read('feature-flags.js');assert.match(source,/id\s*=\s*['"]mobileNavStudy['"]/);assert.match(source,/id\s*=\s*['"]desktopStudyBtn['"]/);assert.match(source,/司法試験学習/);assert.match(source,/window\.location\.href\s*=\s*['"]study\.html['"]/)});
test('study inline JavaScript parses and static verifier covers study',()=>{const source=read('study.html');for(const match of source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi))new vm.Script(match[1],{filename:'study.html:inline'});assert.match(read('scripts/check-static.mjs'),/['"]study\.html['"]/)});
