import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const read=(name)=>fs.readFileSync(new URL(`../${name}`,import.meta.url),'utf8');

test('study page uses query history routing for old and definition quiz views',()=>{const source=read('study.html');for(const view of ['subjects','arguments','past-questions','review','progress','definitions','definition-editor','quiz','quiz-session'])assert.match(source,new RegExp(`['\\"]${view}['\\"]`));assert.match(source,/searchParams\.get\(['"]view['"]\)/);assert.match(source,/searchParams\.set\(['"]view['"],\s*normalized\)/);assert.match(source,/history\.pushState\(/);assert.match(source,/history\.replaceState\(/);assert.match(source,/addEventListener\(['"]popstate['"]/);assert.doesNotMatch(source,/<dialog\b/i)});
test('study page loads modular quiz system',()=>{const source=read('study.html');for(const file of ['vault-payload.js','study-data.js','study-sync.js','study-quiz.js','study-audio.js','study-ai.js','study-offline.js'])assert.match(source,new RegExp(file.replace('.','\\.')))});
test('definition editor exposes editable AI structure and readings',()=>{const source=read('study.html');for(const id of ['definitionSubject','definitionGenre','definitionTitle','definitionModelText','definitionTitlePronunciation','definitionModelPronunciation','memoryUnitsEditor','clozeEditor','analyzeDefinitionBtn','regenerateReadingBtn','saveDefinitionBtn'])assert.match(source,new RegExp(`id=['\\"]${id}['\\"]`))});
test('quiz UI keeps learning machinery hidden',()=>{const source=read('study.html');assert.match(source,/おまかせで始める/);assert.match(source,/範囲を指定する/);assert.match(source,/思い出せない/);assert.match(source,/id=['"]quizProgressBar['"]/);assert.match(source,/id=['"]quizSpeakerBtn['"]/);assert.match(source,/この問題が答えられるようになっています/);assert.doesNotMatch(source,/>\s*Lv\.\d/);assert.doesNotMatch(source,/弱点穴埋め/);assert.doesNotMatch(source,/完全再現/);assert.doesNotMatch(source,/次回はこの.*穴埋め.*再登場/);assert.doesNotMatch(source,/復習期限と弱点から/);assert.doesNotMatch(source,/>\s*8\s*\/\s*10\s*</)});
test('Liquid Glass dock and auth guard remain present',()=>{const source=read('study.html');for(const id of ['studyNavHome','studyNavSubjects','studyNavArguments','studyNavPastQuestions','studyNavReview'])assert.match(source,new RegExp(`id=['\\"]${id}['\\"]`));assert.match(source,/id=['"]studyBottomNav['"]/);assert.match(source,/id=['"]liquidRefraction['"]/);assert.match(source,/--glass-light-x/);assert.match(source,/pointermove[\s\S]*updateGlassLight/);assert.match(source,/pointerdown[\s\S]*glass-pressed/);assert.match(source,/#studyBottomNav::before/);assert.match(source,/#studyBottomNav::after/);assert.match(source,/backdrop-filter:\s*blur\(38px\)\s+saturate\(180%\)\s+contrast\(106%\)/);assert.match(source,/env\(safe-area-inset-bottom\)/);assert.match(source,/prefers-reduced-motion/);assert.match(source,/class=['"]auth-pending['"]/);assert.match(source,/supabase-config\.js/);assert.match(source,/vault-session\.js/);assert.match(source,/mangaReaderSupabaseSession/);assert.match(source,/MangaVault\.loadActive\(\)/);assert.match(source,/window\.location\.replace\(['"]sync\.html['"]\)/);assert.match(source,/window\.location\.replace\(['"]index\.html['"]\)/)});
test('reader still exposes judicial exam study entry',()=>{const source=read('feature-flags.js');assert.match(source,/id\s*=\s*['"]mobileNavStudy['"]/);assert.match(source,/id\s*=\s*['"]desktopStudyBtn['"]/);assert.match(source,/司法試験学習/);assert.match(source,/window\.location\.href\s*=\s*['"]study\.html['"]/)});
test('study inline JavaScript parses and static verifier covers study',()=>{const source=read('study.html');for(const match of source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi))new vm.Script(match[1],{filename:'study.html:inline'});assert.match(read('scripts/check-static.mjs'),/['"]study\.html['"]/)});
